// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrMUKDsUb4tew72vdkeX_v9s-BsSgg9X4',
    appId: '1:125120646156:web:5ebd4c22a0e569b6a4f229',
    messagingSenderId: '125120646156',
    projectId: 'petwalk-14a2a',
    authDomain: 'petwalk-14a2a.firebaseapp.com',
    storageBucket: 'petwalk-14a2a.firebasestorage.app',
    measurementId: 'G-QX7B4ETCEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZEn9-Wj7K__4uH6fZOsGXIejBr1ZXL-U',
    appId: '1:125120646156:android:03a2256bee74ec6fa4f229',
    messagingSenderId: '125120646156',
    projectId: 'petwalk-14a2a',
    storageBucket: 'petwalk-14a2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVEqiv1JKeuMWjISJSyT6oiOY5qy0qtfc',
    appId: '1:125120646156:ios:701388562a1ec660a4f229',
    messagingSenderId: '125120646156',
    projectId: 'petwalk-14a2a',
    storageBucket: 'petwalk-14a2a.firebasestorage.app',
    iosBundleId: 'com.example.deupetwalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVEqiv1JKeuMWjISJSyT6oiOY5qy0qtfc',
    appId: '1:125120646156:ios:701388562a1ec660a4f229',
    messagingSenderId: '125120646156',
    projectId: 'petwalk-14a2a',
    storageBucket: 'petwalk-14a2a.firebasestorage.app',
    iosBundleId: 'com.example.deupetwalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrMUKDsUb4tew72vdkeX_v9s-BsSgg9X4',
    appId: '1:125120646156:web:69c8456ec554162ea4f229',
    messagingSenderId: '125120646156',
    projectId: 'petwalk-14a2a',
    authDomain: 'petwalk-14a2a.firebaseapp.com',
    storageBucket: 'petwalk-14a2a.firebasestorage.app',
    measurementId: 'G-9KYH4YQ5QG',
  );
}
